$axure.loadCurrentPage({
  "url":"注册.html",
  "generationDate":new Date(1458979235686.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"75678179624f45d381a63a6cdf78474e",
    "type":"Axure:Page",
    "name":"注册",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0b20693670c840b8bc95a904227067db",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"23adafa7539c44caae711628187c4222"},
{
          "id":"54f092d407da4c56926bf321aaeb7e75",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "location":{
              "x":50,
              "y":50},
            "size":{
              "width":360,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e151cb8efbc4468d81484ef898ae143d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "location":{
                  "x":50,
                  "y":50},
                "size":{
                  "width":360,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u3.png"}},
{
          "id":"90a2d3d077194d6fbaea45f373a655a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":60,
              "y":110},
            "size":{
              "width":340,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d97a2c50f9a945a38dccc37ec5dbde3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":60,
                  "y":110},
                "size":{
                  "width":340,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}},
{
          "id":"910dec8e01624a7f882da6834cda4660",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":60,
              "y":160},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1ba440765dd4a40bcd401ac214543bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":60,
                  "y":160},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u7.png"}},
{
          "id":"6ef3a384d7f14a33abf8a48dcc6e4916",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":60,
              "y":210},
            "size":{
              "width":340,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41956c5e6ec342a5944ef78309fbc2bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":60,
                  "y":210},
                "size":{
                  "width":340,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}},
{
          "id":"9f55600cf6644a12854e2a339c299dd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":60,
              "y":260},
            "size":{
              "width":340,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f49dd0070214a58b560d13e1ba5b3e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":60,
                  "y":260},
                "size":{
                  "width":340,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}},
{
          "id":"8a2e487ce9de47e6a3c81a9429363a7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":60,
              "y":321},
            "size":{
              "width":340,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"588d2ae96c57498080a14d20e3321980",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":60,
                  "y":321},
                "size":{
                  "width":340,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}},
{
          "id":"1c84d22af9a14b618cc2296da7e8cf0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":270,
              "y":160},
            "size":{
              "width":130,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1daf93b2db9549c787b1e9fcb9126ea2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":270,
                  "y":160},
                "size":{
                  "width":130,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u15.png"}},
{
          "id":"1dda193374034a0d8b75c9a1dbe66ce1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":67},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b979a0a01b94a8da72417e3bea5099e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":67},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "23adafa7539c44caae711628187c4222":{
      "packageId":"23adafa7539c44caae711628187c4222",
      "type":"Axure:Master",
      "name":"基础框架",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"7112620aabdc4d5b91ebe669c2b6edc4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":50,
                "y":50},
              "size":{
                "width":360,
                "height":640}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eb751f4e34bf4004898e31fa475069f4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":50,
                    "y":50},
                  "size":{
                    "width":360,
                    "height":640}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u1.png"}}]}}},
  "objectPaths":{
    "0b20693670c840b8bc95a904227067db":{
      "scriptId":"u0",
      "7112620aabdc4d5b91ebe669c2b6edc4":{
        "scriptId":"u1"},
      "eb751f4e34bf4004898e31fa475069f4":{
        "scriptId":"u2"}},
    "54f092d407da4c56926bf321aaeb7e75":{
      "scriptId":"u3"},
    "e151cb8efbc4468d81484ef898ae143d":{
      "scriptId":"u4"},
    "90a2d3d077194d6fbaea45f373a655a8":{
      "scriptId":"u5"},
    "d97a2c50f9a945a38dccc37ec5dbde3b":{
      "scriptId":"u6"},
    "910dec8e01624a7f882da6834cda4660":{
      "scriptId":"u7"},
    "f1ba440765dd4a40bcd401ac214543bb":{
      "scriptId":"u8"},
    "6ef3a384d7f14a33abf8a48dcc6e4916":{
      "scriptId":"u9"},
    "41956c5e6ec342a5944ef78309fbc2bd":{
      "scriptId":"u10"},
    "9f55600cf6644a12854e2a339c299dd8":{
      "scriptId":"u11"},
    "9f49dd0070214a58b560d13e1ba5b3e2":{
      "scriptId":"u12"},
    "8a2e487ce9de47e6a3c81a9429363a7d":{
      "scriptId":"u13"},
    "588d2ae96c57498080a14d20e3321980":{
      "scriptId":"u14"},
    "1c84d22af9a14b618cc2296da7e8cf0d":{
      "scriptId":"u15"},
    "1daf93b2db9549c787b1e9fcb9126ea2":{
      "scriptId":"u16"},
    "1dda193374034a0d8b75c9a1dbe66ce1":{
      "scriptId":"u17"},
    "1b979a0a01b94a8da72417e3bea5099e":{
      "scriptId":"u18"}}});