$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1458979235585.15),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fea0ed1549cf46d2ada3b1613c18363f",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"14da2de34dd148f38fbc18fe988c01de",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"23adafa7539c44caae711628187c4222"},
{
          "id":"75111cdf2d164e16b287ea6bdf83d3dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "location":{
              "x":50,
              "y":50},
            "size":{
              "width":360,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d638dac5a8014701bf6a2ac1adae3705",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "location":{
                  "x":50,
                  "y":50},
                "size":{
                  "width":360,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u3.png"}},
{
          "id":"beb201d716e347f5a9a8aa177441871f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":99},
            "size":{
              "width":360,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cc93575940a472dbd9e70b07ebbe8a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":99},
                "size":{
                  "width":360,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u5.png"}},
{
          "id":"989ed437c45c465ca9f2a8afddf9ee1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":50,
              "y":248},
            "size":{
              "width":360,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"488462e3778d4632aeace82af3d3b951",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":50,
                  "y":248},
                "size":{
                  "width":360,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u7.png"}},
{
          "id":"2c56e606a5e34cfbb574f7e516327a51",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":293},
            "size":{
              "width":340,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61fdcec8a8df4e5aa5e8405b97cc4d5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":293},
                "size":{
                  "width":340,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u9.png"}},
{
          "id":"e4a41bc0a3ba4a65a83c8e3da4c0c4d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":408},
            "size":{
              "width":340,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ea0a3102e834ac49cb9fd65d4ba439b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":408},
                "size":{
                  "width":340,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u11.png"}},
{
          "id":"eb0296412146444d85875c6910bb484f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":453},
            "size":{
              "width":340,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7575995f1f554846bfaaf6e245ce3a3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":453},
                "size":{
                  "width":340,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u9.png"}},
{
          "id":"aacc5ecbce554a399e7ce470ef9523be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":568},
            "size":{
              "width":340,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5575bb06e94445b8c6300161291c0b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":568},
                "size":{
                  "width":340,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u11.png"}},
{
          "id":"bed6ba72b88647d1814cb676e4821249",
          "label":"蒙牛早餐奶",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":613},
            "size":{
              "width":340,
              "height":75}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"6093ace258164053ba15418cc3228182",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f2ac4c310bdf4c9c9280cdad88ab7b72",
                  "label":"",
                  "parentDynamicPanel":"bed6ba72b88647d1814cb676e4821249",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":340,
                      "height":150}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"370e36a0ae1843ab8d19105b92e59228",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bed6ba72b88647d1814cb676e4821249",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":340,
                          "height":150}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u9.png"}},
{
                  "id":"6e6e6ce98d4046d7a4b20a4611e1cb87",
                  "label":"",
                  "parentDynamicPanel":"bed6ba72b88647d1814cb676e4821249",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":115},
                    "size":{
                      "width":340,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7b562c2005ac4849aea27f9737ee5ae1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bed6ba72b88647d1814cb676e4821249",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":115},
                        "size":{
                          "width":340,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u11.png"}}]}]},
{
          "id":"27c75bfd3a4f4009b3d68fba58672942",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":65},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75aefa6b2eb94fd7b946c415518cc653",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":65},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u22.png"}},
{
          "id":"345277a3ef1a418a81c0e2ea4a5c160f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":65},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8af669fd01c348b2acce0e0a8bbcb163",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":65},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页/u24.png"}}]}},
  "masters":{
    "23adafa7539c44caae711628187c4222":{
      "packageId":"23adafa7539c44caae711628187c4222",
      "type":"Axure:Master",
      "name":"基础框架",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"7112620aabdc4d5b91ebe669c2b6edc4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":50,
                "y":50},
              "size":{
                "width":360,
                "height":640}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eb751f4e34bf4004898e31fa475069f4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":50,
                    "y":50},
                  "size":{
                    "width":360,
                    "height":640}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u1.png"}}]}}},
  "objectPaths":{
    "14da2de34dd148f38fbc18fe988c01de":{
      "scriptId":"u0",
      "7112620aabdc4d5b91ebe669c2b6edc4":{
        "scriptId":"u1"},
      "eb751f4e34bf4004898e31fa475069f4":{
        "scriptId":"u2"}},
    "75111cdf2d164e16b287ea6bdf83d3dc":{
      "scriptId":"u3"},
    "d638dac5a8014701bf6a2ac1adae3705":{
      "scriptId":"u4"},
    "beb201d716e347f5a9a8aa177441871f":{
      "scriptId":"u5"},
    "5cc93575940a472dbd9e70b07ebbe8a9":{
      "scriptId":"u6"},
    "989ed437c45c465ca9f2a8afddf9ee1c":{
      "scriptId":"u7"},
    "488462e3778d4632aeace82af3d3b951":{
      "scriptId":"u8"},
    "2c56e606a5e34cfbb574f7e516327a51":{
      "scriptId":"u9"},
    "61fdcec8a8df4e5aa5e8405b97cc4d5d":{
      "scriptId":"u10"},
    "e4a41bc0a3ba4a65a83c8e3da4c0c4d6":{
      "scriptId":"u11"},
    "9ea0a3102e834ac49cb9fd65d4ba439b":{
      "scriptId":"u12"},
    "eb0296412146444d85875c6910bb484f":{
      "scriptId":"u13"},
    "7575995f1f554846bfaaf6e245ce3a3b":{
      "scriptId":"u14"},
    "aacc5ecbce554a399e7ce470ef9523be":{
      "scriptId":"u15"},
    "b5575bb06e94445b8c6300161291c0b6":{
      "scriptId":"u16"},
    "bed6ba72b88647d1814cb676e4821249":{
      "scriptId":"u17"},
    "f2ac4c310bdf4c9c9280cdad88ab7b72":{
      "scriptId":"u18"},
    "370e36a0ae1843ab8d19105b92e59228":{
      "scriptId":"u19"},
    "6e6e6ce98d4046d7a4b20a4611e1cb87":{
      "scriptId":"u20"},
    "7b562c2005ac4849aea27f9737ee5ae1":{
      "scriptId":"u21"},
    "27c75bfd3a4f4009b3d68fba58672942":{
      "scriptId":"u22"},
    "75aefa6b2eb94fd7b946c415518cc653":{
      "scriptId":"u23"},
    "345277a3ef1a418a81c0e2ea4a5c160f":{
      "scriptId":"u24"},
    "8af669fd01c348b2acce0e0a8bbcb163":{
      "scriptId":"u25"}}});